### ISSUE TITLE
Concat: attribute feature_types disspears

### ISSUE THREAD

**Issue by andreas-wilm** [icbi-lab/scirpy#271] opened 2021-06-14 06:21 UTC
Hi all,

I ran into two related problems with `concat()` and am not sure if the behaviour is as intended and I just don't get it or whether this is a bug. 

The scenario is as follows: I'm loading several samples with `read_10x_h5(.., gex_only=False)` because my samples contains "Gene Expression" and "Antibody Capture" data. The adatas eventually get merged with `concat()` as shown in https://icbi-lab.github.io/scirpy/tutorials/tutorial_io.html. However after `concat()`, the `feature_types` attribute disappears. Why is that?

The other related issue is that even though I can find most feature barcode entries in `adata.var`, not all of them are there. Each of my samples has a number of feature barcodes that are not shared with other samples and those are the ones missing. Is there a way for me retain them? 

Thank you for creating and developing this wonderful toolkit!

Version info:
- airr 1.3.1
- anndata 0.7.6
- scirpy 0.7.0

**Comment by grst** [comment] 2021-06-14 08:43
Hi Andreas, 

thanks for reporting! 

> However after concat(), the feature_types attribute disappears. Why is that?

I don't think that the problem is within `concat` (If it was, it would be an anndata bug). Can you show in more detail how you load the IR data and merge it with the transcriptomics data. I would suspect the problem lies with `merge_with_ir` or `merge_airr_chains`. 

> The other related issue is that even though I can find most feature barcode entries in adata.var, not all of them are there. Each of my samples has a number of feature barcodes that are not shared with other samples and those are the ones missing. Is there a way for me retain them?

This indeed seems to be an anndata-related question and might be better asked there. But I suspect you want an 'outer' join, see [this section](https://anndata.readthedocs.io/en/latest/concatenation.html#inner-and-outer-joins) in the anndata docs.

**Comment by andreas-wilm** [comment] 2021-06-15 08:37
Thanks for the prompt reply Gregor. Thanks also for the pointer to the inner and outer join section of AnnData. This sounds like it will solve my second problem. 

Please see below for a code snippet. I followed the [Scirpy tutorial](https://icbi-lab.github.io/scirpy/tutorials/tutorial_io.html).


    adatas = []
    for sample in samples:
        fvdj = ...
        fgexfbc = ...

        adata_tcr = ir.io.read_10x_vdj(fvdj)
        adata = sc.read_10x_h5(fgexfbc, gex_only=False)
        
        ...
    
        ir.pp.merge_with_ir(adata, adata_tcr)
        adata.var_names_make_unique()
        adata.obs_names_make_unique()
        adata.obs["sample"] = sample

        adatas.append(adata)
        
    # Merge anndata objects
    adata = anndata.concat(adatas)

**Comment by grst** [comment] 2021-06-16 13:06
It seems `adata.concat(..., merge="same")` does the trick. By default anndata discards all variables that are not on the axis that is being aligned. 

I would have expected this to be the default, too, but probably there were reasons why the anndata developers decided against it. 

In any case, this time it's not scirpy's fault (:tada:), so I'm closing the issue.

**Closed by grst** 2021-06-16 13:06 UTC

**Comment by andreas-wilm** [comment] 2021-06-18 02:59
That's it! `merge="same"` did the trick indeed. Thanks so much for your help!
