### ISSUE TITLE
ir.tl.clonotype_network() returns ValueError: value.index does not match parent’s axis 0 names

### ISSUE THREAD

**Issue by chris-rands** [icbi-lab/scirpy#260] opened 2021-04-12 12:10 UTC
I'm getting an error while running `ir.tl.clonotype_network(adata)` using the github dev version (can provide the commit hash if needed). Note I only have TCR data loaded, no matched RNA-seq
```pytb
/path/scirpy/io/_util.py in check_wrapper(*args, **kwargs)
     61             for i in check_args:
     62                 _check_anndata_upgrade_schema(args[i])
---> 63             return f(*args, **kwargs)
     64 
     65         return check_wrapper

/path/scirpy/_tools/_clonotypes.py in clonotype_network(adata, sequence, metric, min_cells, min_nodes, layout, size_aware, base_size, size_power, layout_kwargs, clonotype_key, key_added, inplace, random_state)
    554     # Store results or return
    555     if inplace:
--> 556         adata.obsm[f"X_{key_added}"] = coord_df
    557         params_dict["clonotype_key"] = clonotype_key
    558         params_dict["base_size"] = base_size

/path/anndata/_core/aligned_mapping.py in __setitem__(self, key, value)
    149 
    150     def __setitem__(self, key: str, value: V):
--> 151         value = self._validate_value(value, key)
    152         self._data[key] = value
    153 

/path/anndata/_core/aligned_mapping.py in _validate_value(self, val, key)
    210         ):
    211             # Could probably also re-order index if it’s contained
--> 212             raise ValueError(
    213                 f"value.index does not match parent’s axis {self.axes[0]} names"
    214             )

ValueError: value.index does not match parent’s axis 0 names
```

Spun out from https://github.com/icbi-lab/scirpy/issues/242#issuecomment-817732637 - thanks

**Comment by grst** [comment] 2021-04-12 12:20
Hmm, looking at the comparison of indexes you posted in #242, it seems like `adata.var_names_make_unique()` was called somewhere. The weird thing is that the var_names of `coord_df` are unique, and I definitely don't call `var_names_make_unique` in the scirpy code. 

What does `adata.var_names` look like and does it match `adata.obsm.dim_names`?

**Comment by grst** [comment] 2021-04-12 12:35
And you shouldn't even be able to `define_clonotypes` with non-unique `obs_names` :thinking: 

https://github.com/icbi-lab/scirpy/blob/fa5f6028c7f61e1e0fa06d2c2b3c61b646c626e4/scirpy/ir_dist/_clonotype_neighbors.py#L72-L73

**Comment by chris-rands** [comment] 2021-04-12 18:19
Thanks @grst and apologies I've not been very clear- I have an examples of the error here- can you reproduce?

```
import scirpy as ir
import anndata
adata = ir.datasets.wu2020_3k()
adatas = anndata.concat([adata,adata])
adatas.obs_names_make_unique()
ir.tl.chain_qc(adatas)
ir.tl.define_clonotypes(adatas)
ir.tl.clonotype_network(adatas)
```

**Comment by grst** [comment] 2021-04-12 18:31
Perfect, thanks! 
I'll look into it.

**Comment by grst** [comment] 2021-04-13 09:44
It seems the problem is due to a bug in anndata, which has been fixed in anndata=0.7.6 (just released 2 days ago). 
Can you try updating and check if this fixes the problem? 

I'll make sure to pin anndata 0.7.6 in the requirements.

**Comment by chris-rands** [comment] 2021-04-13 12:08
Thank you, yes, I can confirm that fixes the issue

But unfortunately the `adatas.write("test.h5ad")` fails with the example above
```
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key 'extra_chains' of <class 'h5py._hl.group.Group'> from /.

Above error raised while writing key 'obs' of <class 'h5py._hl.files.File'> from /.
```

h5py version '3.2.1'

**Comment by grst** [comment] 2021-04-13 12:59
Should be fixed now.

**Closed** 2021-04-13 12:58 UTC

**Comment by chris-rands** [comment] 2021-04-13 13:40
Excellent thanks

**Comment by chris-rands** [comment] 2021-04-13 16:51
Another .write() fail after `ir.pl.clonotype_imbalance(adatas, replicate_col="sample", case_label="Lung1", groupby="patient")`
```
TypeError: None of type <class 'NoneType'> is an invalid key. Should be str.

Above error raised while writing key 'uns/clonotype_imbalance/abundance' of <class 'h5py._hl.files.File'> from /.
```

Just reporting it, no a big issue for me as a user, probably another unit test could catch these cases :)
